apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/rad-containers-hmed/cloud-canvas/api:latest
          imagePullPolicy: Always
          resources:
            # Autopilot minimums / defaults
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            # limits:
            #   memory: "512Mi"
            #   cpu: "500m"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: API_TOKEN
              value: foobar
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: postgres-server
                  key: API_POSTGRES_SERVER
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: API_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: API_POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: neondb
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: API_GOOGLE_CLIENT_ID
            - name: CREDENTIAL_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: credential-encryption-key
                  key: API_CREDENTIAL_ENCRYPTION_KEY
            - name: OTEL_SERVICE_NAME
              value: canvas-api
              # valueFrom:
              #   secretKeyRef:
              #     name: otel-service-name
              #     key: API_OTEL_SERVICE_NAME
            # - name: OTEL_EXPORTER_OTLP_HEADERS
            #   valueFrom:
            #     secretKeyRef:
            #       name: otel-exporter-otlp-headers
            #       key: API_OTEL_EXPORTER_OTLP_HEADERS
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-api-key
                  key: API_HONEYCOMB_API_KEY
            - name: HONEYCOMB_DATASET
              value: dev
              # valueFrom:
              #   secretKeyRef:
              #     name: honeycomb-dataset
              #     key: API_HONEYCOMB_DATASET
      # volumes:
      # - name: mysecret
      #   csi:
      #     driver: secrets-store-gke.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: secret-manager
